name: Attach Files To Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}
      - name: sha256sums
        run: |
          sha256sum create-conventional-changelog > sha256sums.txt
      - name: Attach files to release
        env:
          RELEASE_TAG: ${{ steps.vars.outputs.tag }}
        run: >-
          hub release edit
          -m ""
          -a ./create-conventional-changelog
          -a ./sha256sums.txt
          $RELEASE_TAG
